### ISSUE TITLE
print statement that is not compatible with Python 3 in last release

### ISSUE THREAD

**Issue by elainethale** [ibm-watson-data-lab/pixiedust_node#19]
I see from your Python3 milestone that you are working toward Python 3 compatibility and have already merged in many fixes. However, your most recent release (v0.2.0) contains a [fairly new line of code](https://github.com/ibm-watson-data-lab/pixiedust_node/blob/master/pixiedust_node/node.py#L91) that does not work in Python 3. In my notebook I see this right away:

```
import pixiedust_node
```

```
Traceback (most recent call last):

  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-4377929b0946>", line 1, in <module>
    import pixiedust_node

  File "c:\python36\lib\site-packages\pixiedust_node\__init__.py", line 20, in <module>
    from .node import Node, Npm

  File "c:\python36\lib\site-packages\pixiedust_node\node.py", line 91
    print '!!! Warning: store is now deprecated - Node.js global variables are automatically propagated to Python !!!'
                                                                                                                     ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by glynnbird** [comment]
Fixed in `0.2.1`. Thanks for the PR :)
